spring:
  application:
    name: authentication
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT}/eureka/

logging:
  level:
    com.utp.authentication: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive: DEBUG
